### ISSUE TITLE
DataWithBump never used in example

### ISSUE THREAD

**Issue by drew2g** [coral-xyz/sealevel-attacks#7]
https://github.com/project-serum/sealevel-attacks/blob/609e5ade229eaa2b030589020e840c9407bda027/programs/7-bump-seed-canonicalization/secure/src/lib.rs#L41

**Comment by yourarj** [comment]
https://github.com/project-serum/sealevel-attacks/pull/12

**Comment by armaniferrante** [comment]
Done.
